<?php
class Helper{
public static function setting($pdo,$k,$d=''){$s=$pdo->prepare("SELECT svalue FROM app_settings WHERE skey=?");$s->execute([$k]);$r=$s->fetchColumn();return $r!==false?$r:$d;}
public static function tahunAktif($pdo){$s=$pdo->query("SELECT * FROM tahun_anggaran WHERE status='aktif' LIMIT 1");$r=$s->fetch();if(!$r){$s=$pdo->query("SELECT * FROM tahun_anggaran ORDER BY tahun DESC LIMIT 1");$r=$s->fetch();}return $r;}
public static function madrasah($pdo){$m=$pdo->query("SELECT * FROM madrasah WHERE id=1")->fetch()?:[];try{if(!empty($m['kepala_guru_id'])){$s=$pdo->prepare("SELECT nama,nuptk FROM guru WHERE id=?");$s->execute([(int)$m['kepala_guru_id']]);if($g=$s->fetch()){$m['nama_kepala']=$g['nama'];$m['nip_kepala']=$g['nuptk']??'';}}if(!empty($m['bendahara_guru_id'])){$s=$pdo->prepare("SELECT nama,nuptk FROM guru WHERE id=?");$s->execute([(int)$m['bendahara_guru_id']]);if($g=$s->fetch()){$m['nama_bendahara']=$g['nama'];$m['nip_bendahara']=$g['nuptk']??'';}}}catch(Exception $e){}return $m;}
public static function nomorDok($no,$kode='MI-SF'){ $b=(int)date('n');$y=date('Y');return sprintf('%03d',$no).'/RKAM/'.$kode.'/'.Security::romawi($b).'/'.$y;}
public static function persen($a,$b){$b=(float)$b;if($b<=0)return 0;return round(((float)$a/$b)*100,2);}
public static function badgeStatus($s){$m=['draft'=>'bg-gray-200 text-gray-700','diajukan'=>'bg-yellow-100 text-yellow-800','diverifikasi'=>'bg-blue-100 text-blue-800','disetujui'=>'bg-green-100 text-green-800','ditolak'=>'bg-red-100 text-red-800','direvisi'=>'bg-orange-100 text-orange-800','dikunci'=>'bg-slate-800 text-white','aktif'=>'bg-green-100 text-green-800','nonaktif'=>'bg-gray-200 text-gray-600','selesai'=>'bg-slate-200 text-slate-700'];$c=$m[strtolower($s)]??'bg-gray-100';return '<span class="px-2 py-1 rounded text-xs font-semibold '.$c.'">'.htmlspecialchars(self::titleCase($s)).'</span>';}
public static function tglWib($dt){$ts=strtotime((string)$dt);if(!$ts)return '-';$bl=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];return date('j',$ts).' '.$bl[(int)date('n',$ts)-1].' '.date('Y, H:i',$ts).' WIB';}
public static function tglIndo($dt){$ts=strtotime((string)$dt);if(!$ts)return '-';$bl=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];return date('j',$ts).' '.$bl[(int)date('n',$ts)-1].' '.date('Y',$ts);}
public static function timeAgo($dt){$ts=strtotime((string)$dt);if(!$ts)return '-';$d=time()-$ts;if($d<0)$d=0;if($d<10)return 'baru saja';if($d<60)return $d.' dtk lalu';$m=(int)floor($d/60);if($m<60)return $m.' mnt lalu';$h=(int)floor($m/60);if($h<24)return $h.' jam lalu';return self::tglWib($dt);}
public static function logStyle($aksi){$a=strtolower(trim((string)$aksi));$m=['login'=>['fa-right-to-bracket','bg-emerald-100','text-emerald-700'],'login_gagal'=>['fa-triangle-exclamation','bg-red-100','text-red-700'],'logout'=>['fa-right-from-bracket','bg-slate-200','text-slate-600'],'tambah'=>['fa-plus','bg-emerald-100','text-emerald-700'],'edit'=>['fa-pen','bg-amber-100','text-amber-700'],'hapus'=>['fa-trash-can','bg-red-100','text-red-700'],'diajukan'=>['fa-paper-plane','bg-blue-100','text-blue-700'],'diverifikasi'=>['fa-circle-check','bg-blue-100','text-blue-700'],'disetujui'=>['fa-thumbs-up','bg-emerald-100','text-emerald-700'],'ditolak'=>['fa-thumbs-down','bg-red-100','text-red-700'],'direvisi'=>['fa-rotate-left','bg-orange-100','text-orange-700'],'dikunci'=>['fa-lock','bg-slate-800','text-white'],'draft'=>['fa-lock-open','bg-gray-200','text-gray-600'],'backup'=>['fa-floppy-disk','bg-emerald-100','text-emerald-700'],'restore'=>['fa-rotate-left','bg-amber-100','text-amber-700'],'reset_password'=>['fa-key','bg-amber-100','text-amber-700'],'ganti_tahun'=>['fa-calendar-days','bg-violet-100','text-violet-700'],'update'=>['fa-cloud-arrow-down','bg-emerald-100','text-emerald-700'],'impor'=>['fa-file-import','bg-blue-100','text-blue-700']];$r=$m[$a]??['fa-circle-info','bg-blue-100','text-blue-700'];return ['icon'=>$r[0],'bg'=>$r[1],'tx'=>$r[2]];}
public static function titleCase($s){return ucwords(strtolower(trim((string)$s)));}
public static function syncKegiatanToRkam($pdo,$kid){try{$m=$pdo->prepare("SELECT k.*,g.nama AS guru_nama FROM kegiatan k LEFT JOIN guru g ON g.id=k.guru_id WHERE k.id=?");$m->execute([$kid]);$k=$m->fetch();if(!$k)return 0;$pj=$k['guru_nama']??$k['penanggung_jawab'];$s=$pdo->prepare("UPDATE rkam SET kode_kegiatan=?,nama_kegiatan=?,bidang_id=?,tujuan=?,sasaran=?,indikator=?,penanggung_jawab=?,waktu_pelaksanaan=?,prioritas=? WHERE kegiatan_id=? AND status<>'dikunci'");$s->execute([$k['kode'],$k['nama_kegiatan'],$k['bidang_id']?:null,$k['tujuan'],$k['sasaran'],$k['indikator'],$pj,($k['waktu_pelaksanaan']??null)?substr($k['waktu_pelaksanaan'],0,10):null,$k['prioritas']??'sedang',$kid]);return $s->rowCount();}catch(Exception $e){error_log('syncKegiatan: '.$e->getMessage());return 0;}}
public static function alnum($len=4){$ch='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';$o='';for($i=0;$i<$len;$i++)$o.=$ch[random_int(0,strlen($ch)-1)];return $o;}
public static function kodeUnik($pdo,$table,$col,$gen,$try=20){for($i=0;$i<$try;$i++){$k=$gen();$s=$pdo->prepare("SELECT COUNT(*) FROM `$table` WHERE `$col`=?");$s->execute([$k]);if(!$s->fetchColumn())return $k;}return $gen().self::alnum(2);}
public static function initial($nama){$w=preg_split('/\s+/',trim((string)$nama));$w=array_values(array_filter($w));if(!$w)return 'LLN';if(count($w)===1){$s=strtoupper(preg_replace('/[^A-Za-z]/','',$w[0]));return substr($s.'XXX',0,3);}$s='';foreach($w as $x)$s.=strtoupper($x[0]);return substr($s,0,4);}
public static function singkatan($nama){$s=strtoupper(preg_replace('/[^A-Za-z]/','',(string)$nama));if(strlen($s)<=3)return $s;return substr($s,0,3);}
public static function autoKode($pdo,$table,$nama=''){switch($table){
case 'bidang': return self::kodeUnik($pdo,'bidang','kode',fn()=>'B'.self::alnum(3));
case 'jenis_belanja': return self::kodeUnik($pdo,'jenis_belanja','kode',fn()=>'JB'.self::alnum(3));
case 'kegiatan': return self::kodeUnik($pdo,'kegiatan','kode',fn()=>'KGT-'.self::alnum(4));
case 'rekening': for($i=1;$i<=99;$i++){$k='5.1.'.sprintf('%02d',$i);$s=$pdo->prepare("SELECT COUNT(*) FROM rekening WHERE kode=?");$s->execute([$k]);if(!$s->fetchColumn())return $k;} return self::kodeUnik($pdo,'rekening','kode',fn()=>'5.'.random_int(1,9).'.'.sprintf('%02d',random_int(1,99)));
case 'sumber_dana': $base=self::initial($nama);$k=$base;for($i=1;$i<=50;$i++){$s=$pdo->prepare("SELECT COUNT(*) FROM sumber_dana WHERE kode=?");$s->execute([$k]);if(!$s->fetchColumn())return $k;$k=$base.$i;} return $base.self::alnum(2);
case 'satuan': $base=self::singkatan($nama);$k=$base;for($i=1;$i<=50;$i++){$s=$pdo->prepare("SELECT COUNT(*) FROM satuan WHERE kode=?");$s->execute([$k]);if(!$s->fetchColumn())return $k;$k=$base.$i;} return $k;
case 'guru': for($i=1;$i<=999;$i++){$k='GRU-'.sprintf('%03d',$i);$s=$pdo->prepare("SELECT COUNT(*) FROM guru WHERE kode=?");$s->execute([$k]);if(!$s->fetchColumn())return $k;} return self::kodeUnik($pdo,'guru','kode',fn()=>'GRU-'.self::alnum(3));
case 'jabatan': for($i=1;$i<=999;$i++){$k='JBT-'.sprintf('%03d',$i);$s=$pdo->prepare("SELECT COUNT(*) FROM jabatan WHERE kode=?");$s->execute([$k]);if(!$s->fetchColumn())return $k;} return self::kodeUnik($pdo,'jabatan','kode',fn()=>'JBT-'.self::alnum(3));
default: return null;}}
}
