<?php
$th=Helper::tahunAktif($pdo);$tid=(int)($_GET['tahun']??($th['id']??0));
$tahun=$pdo->query("SELECT * FROM tahun_anggaran ORDER BY tahun DESC")->fetchAll();
$jenis=$_GET['jenis']??'rkam';
$rk=$pdo->prepare("SELECT k.*,b.nama_bidang,(SELECT COALESCE(SUM(jumlah),0) FROM realisasi WHERE rkam_id=k.id) AS jml_real FROM rkam k LEFT JOIN bidang b ON b.id=k.bidang_id WHERE k.tahun_id=? ORDER BY k.id");$rk->execute([$tid]);$rk=$rk->fetchAll();
$perSumber=$pdo->query("SELECT s.nama_sumber_dana,COALESCE((SELECT SUM(rs.jumlah) FROM rkam_sumber_dana rs JOIN rkam k ON k.id=rs.rkam_id WHERE rs.sumber_dana_id=s.id AND k.tahun_id=$tid),0) agg,COALESCE((SELECT SUM(r.jumlah) FROM realisasi r JOIN rkam k ON k.id=r.rkam_id WHERE r.sumber_dana_id=s.id AND k.tahun_id=$tid),0) rea FROM sumber_dana s")->fetchAll();
$perBidang=$pdo->query("SELECT b.nama_bidang,COUNT(k.id) jml,COALESCE(SUM(k.total_anggaran),0) agg FROM bidang b LEFT JOIN rkam k ON k.bidang_id=b.id AND k.tahun_id=$tid GROUP BY b.id")->fetchAll();
foreach($perBidang as &$pb){$pb['rea']=$pdo->query("SELECT COALESCE(SUM(r.jumlah),0) FROM realisasi r JOIN rkam k ON k.id=r.rkam_id WHERE k.bidang_id=(SELECT id FROM bidang WHERE nama_bidang=".$pdo->quote($pb['nama_bidang']).") AND k.tahun_id=$tid")->fetchColumn();}
unset($pb);
$perBulan=[];for($m=1;$m<=12;$m++){$s=$pdo->prepare("SELECT COALESCE(SUM(r.jumlah),0) FROM realisasi r JOIN rkam k ON k.id=r.rkam_id WHERE k.tahun_id=? AND MONTH(r.tanggal_transaksi)=?");$s->execute([$tid,$m]);$perBulan[$m]=(float)$s->fetchColumn();}
$trans=$pdo->prepare("SELECT r.*,k.nama_kegiatan FROM realisasi r JOIN rkam k ON k.id=r.rkam_id WHERE k.tahun_id=? ORDER BY r.tanggal_transaksi DESC LIMIT 200");$trans->execute([$tid]);$trans=$trans->fetchAll();
?>
<div class="flex flex-wrap items-center gap-2 mb-3 no-print text-sm">
<div class="font-extrabold text-emerald-900"><?php $lt2=['rkam'=>'Laporan RKAM','realisasi'=>'Laporan Realisasi','sumber'=>'Laporan Per Sumber Dana','bidang'=>'Laporan Per Bidang','bulanan'=>'Laporan Bulanan','transaksi'=>'Laporan Transaksi']; echo $lt2[$jenis]??'Laporan'; ?></div>
<form method="GET" action="<?=BASE_URL?>laporan/<?=$jenis?>" class="flex gap-2 ml-auto">
<select name="tahun" class="border rounded p-1.5"><?php foreach($tahun as $t):?><option value="<?=$t['id']?>" <?=($tid==$t['id']?'selected':'')?>><?=$t['tahun']?></option><?php endforeach;?></select><button class="bg-slate-700 text-white px-3 rounded">Tampilkan</button></form>
<a href="<?=BASE_URL?>print/<?=$jenis?>?tahun=<?=$tid?>" target="_blank" title="Cetak" class="bg-slate-700 hover:bg-slate-800 text-white w-9 h-9 rounded-xl inline-flex items-center justify-center"><i class="fa-solid fa-print"></i></a>
<a href="<?=BASE_URL?>export/csv?jenis=<?=$jenis?>&tahun=<?=$tid?>" title="Excel/CSV" class="bg-green-700 hover:bg-green-800 text-white w-9 h-9 rounded-xl inline-flex items-center justify-center"><i class="fa-solid fa-file-excel"></i></a></div>
<div class="bg-white rounded shadow p-4 overflow-auto text-sm">
<?php if($jenis==='rkam'||$jenis==='realisasi'):?><table class="w-full min-w-[700px]"><thead><tr class="border-b text-left bg-gray-50"><th class="p-2">Kegiatan</th><th class="p-2 text-right">Anggaran</th><th class="p-2 text-right">Realisasi</th><th class="p-2 text-right">Sisa</th><th class="p-2">%</th></tr></thead><tbody>
<?php $ta=0;$tr=0;foreach($rk as $r):$sisa=$r['total_anggaran']-$r['jml_real'];$ta+=$r['total_anggaran'];$tr+=$r['jml_real'];?><tr class="border-b"><td class="p-2"><?=Security::e($r['nama_kegiatan'])?></td><td class="p-2 text-right"><?=Security::rupiah($r['total_anggaran'])?></td><td class="p-2 text-right"><?=Security::rupiah($r['jml_real'])?></td><td class="p-2 text-right"><?=Security::rupiah($sisa)?></td><td class="p-2"><?=Helper::persen($r['jml_real'],$r['total_anggaran'])?>%</td></tr><?php endforeach;?>
<tr class="font-bold"><td class="p-2">TOTAL</td><td class="p-2 text-right"><?=Security::rupiah($ta)?></td><td class="p-2 text-right"><?=Security::rupiah($tr)?></td><td class="p-2 text-right"><?=Security::rupiah($ta-$tr)?></td><td class="p-2"><?=Helper::persen($tr,$ta)?>%</td></tr></tbody></table>
<?php elseif($jenis==='sumber'):?><table class="w-full"><thead><tr class="border-b text-left bg-gray-50"><th class="p-2">Sumber</th><th class="p-2 text-right">Anggaran</th><th class="p-2 text-right">Realisasi</th><th class="p-2 text-right">Sisa</th></tr></thead><tbody><?php foreach($perSumber as $r):?><tr class="border-b"><td class="p-2"><?=Security::e($r['nama_sumber_dana'])?></td><td class="p-2 text-right"><?=Security::rupiah($r['agg'])?></td><td class="p-2 text-right"><?=Security::rupiah($r['rea'])?></td><td class="p-2 text-right"><?=Security::rupiah($r['agg']-$r['rea'])?></td></tr><?php endforeach;?></tbody></table>
<?php elseif($jenis==='bidang'):?><table class="w-full"><thead><tr class="border-b text-left bg-gray-50"><th class="p-2">Bidang</th><th class="p-2">Jumlah</th><th class="p-2 text-right">Anggaran</th><th class="p-2 text-right">Realisasi</th><th class="p-2 text-right">Sisa</th></tr></thead><tbody><?php foreach($perBidang as $r):?><tr class="border-b"><td class="p-2"><?=Security::e($r['nama_bidang'])?></td><td class="p-2"><?=$r['jml']?></td><td class="p-2 text-right"><?=Security::rupiah($r['agg'])?></td><td class="p-2 text-right"><?=Security::rupiah($r['rea'])?></td><td class="p-2 text-right"><?=Security::rupiah($r['agg']-$r['rea'])?></td></tr><?php endforeach;?></tbody></table>
<?php elseif($jenis==='bulanan'):?><table class="w-full"><thead><tr class="border-b text-left bg-gray-50"><th class="p-2">Bulan</th><th class="p-2 text-right">Realisasi</th></tr></thead><tbody><?php $nmB=['','Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember']; foreach($perBulan as $m=>$v):?><tr class="border-b"><td class="p-2"><?=$nmB[$m]?></td><td class="p-2 text-right"><?=Security::rupiah($v)?></td></tr><?php endforeach;?></tbody></table>
<?php else:?><table class="w-full min-w-[700px]"><thead><tr class="border-b text-left bg-gray-50"><th class="p-2">Tanggal</th><th class="p-2">Kegiatan</th><th class="p-2">Uraian</th><th class="p-2 text-right">Jumlah</th></tr></thead><tbody><?php foreach($trans as $r):?><tr class="border-b"><td class="p-2"><?=Security::e($r['tanggal_transaksi'])?></td><td class="p-2"><?=Security::e($r['nama_kegiatan'])?></td><td class="p-2"><?=Security::e($r['uraian'])?></td><td class="p-2 text-right"><?=Security::rupiah($r['jumlah'])?></td></tr><?php endforeach;?></tbody></table><?php endif;?></div>
