<?php
$jenis=$arg??($_GET['jenis']??'rkam'); $tid=(int)($_GET['tahun']??(Helper::tahunAktif($pdo)['id']??0));
$m=Helper::madrasah($pdo); $th=$pdo->prepare("SELECT * FROM tahun_anggaran WHERE id=?");$th->execute([$tid]);$th=$th->fetch();
$rk=$pdo->prepare("SELECT k.*,b.nama_bidang,(SELECT COALESCE(SUM(jumlah),0) FROM realisasi WHERE rkam_id=k.id) AS jml_real FROM rkam k LEFT JOIN bidang b ON b.id=k.bidang_id WHERE k.tahun_id=? ORDER BY k.id");$rk->execute([$tid]);$rk=$rk->fetchAll();
$perSumber=$pdo->query("SELECT s.id,s.kode,s.nama_sumber_dana,COALESCE((SELECT SUM(rs.jumlah) FROM rkam_sumber_dana rs JOIN rkam k ON k.id=rs.rkam_id WHERE rs.sumber_dana_id=s.id AND k.tahun_id=$tid),0) agg,COALESCE((SELECT SUM(r.jumlah) FROM realisasi r JOIN rkam k ON k.id=r.rkam_id WHERE k.tahun_id=$tid AND r.sumber_dana_id=s.id),0) rea FROM sumber_dana s WHERE s.status='aktif' ORDER BY s.nama_sumber_dana")->fetchAll();
$perBidang=$pdo->query("SELECT b.nama_bidang,COUNT(k.id) jml,COALESCE(SUM(k.total_anggaran),0) agg FROM bidang b LEFT JOIN rkam k ON k.bidang_id=b.id AND k.tahun_id=$tid GROUP BY b.id")->fetchAll();
foreach($perBidang as &$pb){$pb['rea']=$pdo->query("SELECT COALESCE(SUM(r.jumlah),0) FROM realisasi r JOIN rkam k ON k.id=r.rkam_id WHERE k.bidang_id=(SELECT id FROM bidang WHERE nama_bidang=".$pdo->quote($pb['nama_bidang']).") AND k.tahun_id=$tid")->fetchColumn();}
unset($pb);
$perBulan=[];for($mm=1;$mm<=12;$mm++){$s=$pdo->prepare("SELECT COALESCE(SUM(r.jumlah),0) FROM realisasi r JOIN rkam k ON k.id=r.rkam_id WHERE k.tahun_id=? AND MONTH(r.tanggal_transaksi)=?");$s->execute([$tid,$mm]);$perBulan[$mm]=(float)$s->fetchColumn();}
$trans=$pdo->prepare("SELECT r.*,k.nama_kegiatan FROM realisasi r JOIN rkam k ON k.id=r.rkam_id WHERE k.tahun_id=? ORDER BY r.tanggal_transaksi DESC LIMIT 200");$trans->execute([$tid]);$trans=$trans->fetchAll();
$hb=[1=>'Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember']; $tglCetak=date('j').' '.$hb[(int)date('n')].' '.date('Y');
$qrK='Ditandatangani secara elektronik | '.($m['nama_madrasah']??'').' | Kepala Madrasah: '.($m['nama_kepala']??'').' / NIP '.($m['nip_kepala']??'-').' | Laporan '.$jenis.' Tahun '.($th['tahun']??'').' | '.$tglCetak;
$qrB='Ditandatangani secara elektronik | '.($m['nama_madrasah']??'').' | Bendahara: '.($m['nama_bendahara']??'').' / NIP '.($m['nip_bendahara']??'-').' | Laporan '.$jenis.' Tahun '.($th['tahun']??'').' | '.$tglCetak;
$lt=['rkam'=>'RKAM','realisasi'=>'Realisasi','sumber'=>'Per Sumber Dana','bidang'=>'Per Bidang','bulanan'=>'Bulanan','transaksi'=>'Transaksi']; $judulLap=$lt[$jenis]??'RKAM';
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><title>Cetak <?=Security::e($judulLap)?></title>
<script src="https://cdn.tailwindcss.com"></script><style>@media print{.no-print{display:none}}</style></head>
<body class="p-8 max-w-4xl mx-auto text-sm" onload="window.print()">
<div class="text-center border-b-2 border-black pb-3 mb-4">
<div class="flex items-center justify-center gap-3">
<?php if(!empty($m['logo'])&&is_file(__DIR__.'/../../uploads/logo/'.$m['logo'])):?><img src="<?=BASE_URL?>uploads/logo/<?=Security::e($m['logo'])?>" style="width:64px;height:64px;object-fit:contain"><?php endif;?>
<div><div class="font-bold text-xl"><?=Security::e($m['nama_madrasah']??'Madrasah')?></div>
<div class="text-xs"><?=Security::e(trim(($m['alamat']??'').' '.($m['desa']??'').' '.($m['kecamatan']??'').' '.($m['kabupaten']??'')))?> • NSM <?=Security::e($m['nsm']??'-')?> • NPSN <?=Security::e($m['npsn']??'-')?></div></div></div>
<div class="font-bold mt-2 uppercase">Laporan <?=Security::e($judulLap)?> Tahun <?=Security::e($th['tahun']??'')?></div></div>
<?php if($jenis==='rkam'):?>
<table class="w-full border-collapse border border-black"><thead><tr class="bg-gray-100"><th class="border border-black p-1 text-left">Kode</th><th class="border border-black p-1 text-left">Kegiatan</th><th class="border border-black p-1 text-left">Bidang</th><th class="border border-black p-1 text-left">Penanggung Jawab</th><th class="border border-black p-1">Status</th><th class="border border-black p-1">Anggaran</th></tr></thead><tbody>
<?php $ta=0;foreach($rk as $r):$ta+=$r['total_anggaran'];?><tr><td class="border border-black p-1"><?=Security::e($r['kode_kegiatan']??'-')?></td><td class="border border-black p-1"><?=Security::e($r['nama_kegiatan'])?></td><td class="border border-black p-1"><?=Security::e($r['nama_bidang']??'-')?></td><td class="border border-black p-1"><?=Security::e($r['penanggung_jawab']??'-')?></td><td class="border border-black p-1 text-center"><?=Security::e($r['status'])?></td><td class="border border-black p-1 text-right"><?=number_format($r['total_anggaran'],0,',','.')?></td></tr><?php endforeach;?>
<tr class="font-bold"><td class="border border-black p-1" colspan="5">TOTAL ANGGARAN</td><td class="border border-black p-1 text-right"><?=number_format($ta,0,',','.')?></td></tr></tbody></table>
<?php elseif($jenis==='realisasi'):?>
<table class="w-full border-collapse border border-black"><thead><tr class="bg-gray-100"><th class="border border-black p-1 text-left">Kegiatan</th><th class="border border-black p-1">Anggaran</th><th class="border border-black p-1">Realisasi</th><th class="border border-black p-1">Sisa</th><th class="border border-black p-1">%</th></tr></thead><tbody>
<?php $ta=0;$tr=0;foreach($rk as $r):$ta+=$r['total_anggaran'];$tr+=$r['jml_real'];?><tr><td class="border border-black p-1"><?=Security::e($r['nama_kegiatan'])?></td><td class="border border-black p-1 text-right"><?=number_format($r['total_anggaran'],0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($r['jml_real'],0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($r['total_anggaran']-$r['jml_real'],0,',','.')?></td><td class="border border-black p-1 text-center"><?=Helper::persen($r['jml_real'],$r['total_anggaran'])?>%</td></tr><?php endforeach;?>
<tr class="font-bold"><td class="border border-black p-1">TOTAL</td><td class="border border-black p-1 text-right"><?=number_format($ta,0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($tr,0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($ta-$tr,0,',','.')?></td><td class="border border-black p-1 text-center"><?=Helper::persen($tr,$ta)?>%</td></tr></tbody></table>
<?php elseif($jenis==='sumber'):?>
<table class="w-full border-collapse border border-black"><thead><tr class="bg-gray-100"><th class="border border-black p-1 text-left">Sumber</th><th class="border border-black p-1">Anggaran</th><th class="border border-black p-1">Realisasi</th><th class="border border-black p-1">Sisa</th></tr></thead><tbody>
<?php $tA=0;$tR=0;foreach($perSumber as $r):$tA+=$r['agg'];$tR+=$r['rea'];?><tr><td class="border border-black p-1"><?=Security::e($r['nama_sumber_dana'])?> (<?=Security::e($r['kode']??'')?>)</td><td class="border border-black p-1 text-right"><?=number_format($r['agg'],0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($r['rea'],0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($r['agg']-$r['rea'],0,',','.')?></td></tr><?php endforeach;?>
<tr class="font-bold"><td class="border border-black p-1">TOTAL</td><td class="border border-black p-1 text-right"><?=number_format($tA,0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($tR,0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($tA-$tR,0,',','.')?></td></tr></tbody></table>
<?php foreach($perSumber as $r): $det=$pdo->prepare("SELECT k.nama_kegiatan,COALESCE((SELECT SUM(rs.jumlah) FROM rkam_sumber_dana rs WHERE rs.rkam_id=k.id AND rs.sumber_dana_id=?),0) agg,COALESCE((SELECT SUM(r2.jumlah) FROM realisasi r2 WHERE r2.rkam_id=k.id AND r2.sumber_dana_id=?),0) rea FROM rkam k WHERE k.tahun_id=? AND (EXISTS(SELECT 1 FROM rkam_sumber_dana rs WHERE rs.rkam_id=k.id AND rs.sumber_dana_id=?) OR EXISTS(SELECT 1 FROM realisasi r3 WHERE r3.rkam_id=k.id AND r3.sumber_dana_id=?)) ORDER BY k.nama_kegiatan"); $det->execute([$r['id'],$r['id'],$tid,$r['id'],$r['id']]); $dd=$det->fetchAll(); if(!$dd)continue; ?>
<div class="font-bold mt-4 mb-1">Rincian <?=Security::e($r['nama_sumber_dana'])?></div>
<table class="w-full border-collapse border border-black"><thead><tr class="bg-gray-100"><th class="border border-black p-1 text-left">Kegiatan</th><th class="border border-black p-1">Anggaran</th><th class="border border-black p-1">Realisasi</th><th class="border border-black p-1">Sisa</th></tr></thead><tbody><?php foreach($dd as $x):?><tr><td class="border border-black p-1"><?=Security::e($x['nama_kegiatan'])?></td><td class="border border-black p-1 text-right"><?=number_format($x['agg'],0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($x['rea'],0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($x['agg']-$x['rea'],0,',','.')?></td></tr><?php endforeach;?></tbody></table><?php endforeach; ?>
<?php elseif($jenis==='bidang'):?>
<table class="w-full border-collapse border border-black"><thead><tr class="bg-gray-100"><th class="border border-black p-1 text-left">Bidang</th><th class="border border-black p-1">Jumlah</th><th class="border border-black p-1">Anggaran</th><th class="border border-black p-1">Realisasi</th><th class="border border-black p-1">Sisa</th></tr></thead><tbody><?php foreach($perBidang as $r):?><tr><td class="border border-black p-1"><?=Security::e($r['nama_bidang'])?></td><td class="border border-black p-1 text-center"><?=$r['jml']?></td><td class="border border-black p-1 text-right"><?=number_format($r['agg'],0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($r['rea'],0,',','.')?></td><td class="border border-black p-1 text-right"><?=number_format($r['agg']-$r['rea'],0,',','.')?></td></tr><?php endforeach;?></tbody></table>
<?php elseif($jenis==='bulanan'):?>
<table class="w-full border-collapse border border-black"><thead><tr class="bg-gray-100"><th class="border border-black p-1 text-left">Bulan</th><th class="border border-black p-1">Realisasi</th></tr></thead><tbody><?php $totB=0;foreach($perBulan as $bl=>$v):$totB+=$v;?><tr><td class="border border-black p-1"><?=$hb[$bl]?></td><td class="border border-black p-1 text-right"><?=number_format($v,0,',','.')?></td></tr><?php endforeach;?><tr class="font-bold"><td class="border border-black p-1">TOTAL</td><td class="border border-black p-1 text-right"><?=number_format($totB,0,',','.')?></td></tr></tbody></table>
<?php else:?>
<table class="w-full border-collapse border border-black"><thead><tr class="bg-gray-100"><th class="border border-black p-1 text-left">Tanggal</th><th class="border border-black p-1 text-left">Kegiatan</th><th class="border border-black p-1 text-left">Uraian</th><th class="border border-black p-1">Jumlah</th></tr></thead><tbody><?php $totT=0;foreach($trans as $r):$totT+=$r['jumlah'];?><tr><td class="border border-black p-1"><?=Security::e($r['tanggal_transaksi'])?></td><td class="border border-black p-1"><?=Security::e($r['nama_kegiatan'])?></td><td class="border border-black p-1"><?=Security::e($r['uraian'])?></td><td class="border border-black p-1 text-right"><?=number_format($r['jumlah'],0,',','.')?></td></tr><?php endforeach;?><tr class="font-bold"><td class="border border-black p-1" colspan="3">TOTAL</td><td class="border border-black p-1 text-right"><?=number_format($totT,0,',','.')?></td></tr></tbody></table>
<?php endif;?>
<div class="flex justify-between mt-10 text-center"><div>Mengetahui,<br>Kepala Madrasah<br><img src="https://api.qrserver.com/v1/create-qr-code/?size=110x110&data=<?=urlencode($qrK)?>" style="width:110px;height:110px;margin:8px auto 4px" alt="QR Kepala"><b><u><?=Security::e($m['nama_kepala']??'...')?></u></b><br>NIP. <?=Security::e($m['nip_kepala']??'-')?></div>
<div><?=Security::e($m['kabupaten']??'')?>, <?=Security::e($tglCetak)?><br>Bendahara<br><img src="https://api.qrserver.com/v1/create-qr-code/?size=110x110&data=<?=urlencode($qrB)?>" style="width:110px;height:110px;margin:8px auto 4px" alt="QR Bendahara"><b><u><?=Security::e($m['nama_bendahara']??'...')?></u></b><br>NIP. <?=Security::e($m['nip_bendahara']??'-')?></div></div>
<div class="no-print mt-6 text-center"><button onclick="window.print()" class="bg-slate-800 text-white px-4 py-2 rounded">Cetak</button></div>
</body></html>
