<?php
$tab=$_GET['tab']??'bidang';
$tabs=['bidang'=>'Bidang','sumber_dana'=>'Sumber Dana','jenis_belanja'=>'Jenis Belanja','satuan'=>'Satuan','rekening'=>'Rekening','kegiatan'=>'Kegiatan','guru'=>'Guru','tahun_anggaran'=>'Tahun Anggaran'];
if(!isset($tabs[$tab]))$tab='bidang';
$cols=['bidang'=>['kode'=>'Kode','nama_bidang'=>'Nama Bidang','keterangan'=>'Keterangan','status'=>'Status'],'sumber_dana'=>['kode'=>'Kode','nama_sumber_dana'=>'Nama Sumber Dana','jumlah'=>'Pagu (Rp)','jml_anggaran'=>'Terpakai RKAM','jml_kegiatan'=>'Jml Kegiatan','keterangan'=>'Keterangan','status'=>'Status'],'jenis_belanja'=>['kode'=>'Kode','nama'=>'Nama','keterangan'=>'Keterangan','status'=>'Status'],'satuan'=>['kode'=>'Kode','nama_satuan'=>'Nama Satuan','keterangan'=>'Keterangan','status'=>'Status'],'rekening'=>['kode'=>'Kode','nama_rekening'=>'Nama Rekening','kelompok'=>'Kelompok','jenis_belanja_id'=>'Jenis Belanja','keterangan'=>'Keterangan','status'=>'Status'],'kegiatan'=>['kode'=>'Kode','nama_kegiatan'=>'Nama Kegiatan','bidang_id'=>'Bidang','volume'=>'Volume','guru_id'=>'Penanggung Jawab','waktu_pelaksanaan'=>'Waktu Pelaksanaan','prioritas'=>'Prioritas','status'=>'Status'],'guru'=>['kode'=>'Kode','nama'=>'Nama Guru','nip'=>'NIP','jabatan'=>'Jabatan','mapel'=>'Mapel','no_hp'=>'No HP','status'=>'Status'],'tahun_anggaran'=>['tahun'=>'Tahun','tanggal_mulai'=>'Tanggal Mulai','tanggal_selesai'=>'Tanggal Selesai','status'=>'Status','keterangan'=>'Keterangan']];
if($tab==='sumber_dana'){$rows=$pdo->query("SELECT s.*,(SELECT COALESCE(SUM(rs.jumlah),0) FROM rkam_sumber_dana rs JOIN rkam k ON k.id=rs.rkam_id WHERE rs.sumber_dana_id=s.id) AS jml_anggaran,(SELECT COUNT(*) FROM rkam_sumber_dana rs JOIN rkam k ON k.id=rs.rkam_id WHERE rs.sumber_dana_id=s.id) AS jml_kegiatan FROM sumber_dana s ORDER BY s.id DESC LIMIT 200")->fetchAll();}else{$rows=$pdo->query("SELECT * FROM `$tab` ORDER BY id DESC LIMIT 200")->fetchAll();}
$bid=$pdo->query("SELECT * FROM bidang WHERE status='aktif'")->fetchAll();
$jb=$pdo->query("SELECT * FROM jenis_belanja")->fetchAll();
$bidMap=[];foreach($bid as $b)$bidMap[$b['id']]=$b['nama_bidang'];
$jbMap=[];foreach($jb as $j)$jbMap[$j['id']]=$j['nama'];
$GRU=$pdo->query("SELECT * FROM guru ORDER BY nama")->fetchAll();
$gruMap=[];foreach($GRU as $g)$gruMap[$g['id']]=$g['nama'];
function cellVal($tab,$c,$r,$bidMap,$jbMap,$gruMap=[]){$v=$r[$c]??'';if($c==='bidang_id')return $bidMap[$v]??'-';if($c==='jenis_belanja_id')return $jbMap[$v]??'-';if($c==='guru_id')return $gruMap[$v]??($r['penanggung_jawab']??'-');if($c==='status'||$c==='prioritas')return Helper::titleCase($v);if($c==='jml_anggaran'||$c==='jumlah')return Security::rupiah($v);if($c==='volume'&&$v!=='')return number_format((float)$v,0,',','.');if(in_array($c,['tanggal_mulai','tanggal_selesai','waktu_pelaksanaan'])&&$v)return Helper::tglIndo($v);return $v;}
?>
<div class="flex flex-wrap items-center gap-2 mb-4 no-print">
<div class="font-extrabold text-emerald-900">Master <?=$tabs[$tab]?></div>
<button onclick="masterForm(0)" title="Tambah <?=$tabs[$tab]?>" class="ml-auto bg-emerald-700 hover:bg-emerald-800 text-white w-10 h-10 rounded-2xl text-sm shadow"><i class="fa-solid fa-plus"></i></button></div>
<div class="bg-white rounded shadow overflow-auto">
<?php if(!$rows):?><div class="p-10 text-center text-gray-500">Belum ada data.<br><button onclick="masterForm(0)" title="Tambah <?=$tabs[$tab]?>" class="mt-2 bg-emerald-700 hover:bg-emerald-800 text-white w-11 h-11 rounded-2xl shadow"><i class="fa-solid fa-plus"></i></button></div>
<?php else:?><table class="w-full text-sm"><thead><tr class="bg-gray-50 border-b"><th class="p-2 w-10 text-left">No</th><?php foreach($cols[$tab] as $c=>$lbl):?><th class="p-2 text-left"><?=Security::e($lbl)?></th><?php endforeach;?><th class="p-2 no-print">Aksi</th></tr></thead>
<tbody><?php $no=1;foreach($rows as $r):?><tr class="border-b hover:bg-gray-50">
<td class="p-2"><?=$no++?></td>
<?php foreach($cols[$tab] as $c=>$lbl):?><td class="p-2"><?=Security::e(cellVal($tab,$c,$r,$bidMap,$jbMap,$gruMap))?></td><?php endforeach;?>
<td class="p-2 whitespace-nowrap no-print"><button onclick='masterForm(<?=$r['id']?>,<?=json_encode($r,JSON_HEX_APOS|JSON_HEX_QUOT)?>)' title="Edit" class="btn-ic btn-edit"><i class="fa-solid fa-pen-to-square"></i></button> <button onclick="masterDel(<?=$r['id']?>)" title="Hapus" class="btn-ic btn-del"><i class="fa-solid fa-trash-can"></i></button></td></tr><?php endforeach;?></tbody></table><?php endif;?></div>
<script>
const TAB='<?=$tab?>',BID=<?=json_encode($bid)?>,JB=<?=json_encode($jb)?>,SATL=<?=json_encode($pdo->query("SELECT * FROM satuan WHERE status='aktif' ORDER BY nama_satuan")->fetchAll())?>,GRU=<?=json_encode($GRU)?>;
function fld(n,v,l,type,extra){return `<div class="mb-2"><label class="text-xs font-bold" style="text-transform:capitalize">${l}</label><input type="${type||'text'}" name="${n}" value="${(v??'').toString().replaceAll('"','')}" class="w-full border rounded p-2 mt-1" ${extra||''}></div>`;}
function selFld(n,v,l,opts){return `<div class="mb-2"><label class="text-xs font-bold" style="text-transform:capitalize">${l}</label><select name="${n}" class="w-full border rounded p-2 mt-1">${opts}</select></div>`;}
function masterForm(id,d){d=d||{};let h=`<div class="flex justify-between items-center mb-3"><b>${id?'Edit':'Tambah'} <?=$tabs[$tab]?></b><button type="button" onclick="closeModal()" title="Tutup" class="w-8 h-8 rounded-full bg-red-50 border border-red-200 text-red-600 hover:bg-red-100 flex items-center justify-center"><i class="fa-solid fa-xmark"></i></button></div><form onsubmit="masterSave(event,${id})">`;
const LBL={kode:'Kode',nama_bidang:'Nama Bidang',nama_sumber_dana:'Nama Sumber Dana',nama:'Nama',nama_satuan:'Nama Satuan',nama_rekening:'Nama Rekening',nama_kegiatan:'Nama Kegiatan',tahun:'Tahun',kelompok:'Kelompok',keterangan:'Keterangan',bidang_id:'Bidang',jenis_belanja_id:'Jenis Belanja',status:'Status',tanggal_mulai:'Tanggal Mulai',tanggal_selesai:'Tanggal Selesai',prioritas:'Prioritas',guru_id:'Penanggung Jawab (Guru)',nama_guru:'Nama Guru',nip:'NIP',jabatan:'Jabatan',mapel:'Mapel / Bidang',no_hp:'No HP'};
const lb=k=>LBL[k]||k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const LBL2=Object.assign({},LBL,{jumlah:'Jumlah (Rp)'});
const lb2=k=>LBL2[k]||k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const c={bidang:['nama_bidang'],sumber_dana:['nama_sumber_dana','jumlah'],jenis_belanja:['nama'],satuan:['nama_satuan'],rekening:['nama_rekening','kelompok'],kegiatan:['nama_kegiatan'],guru:['nama','nip','jabatan','mapel','no_hp'],tahun_anggaran:['tahun']}[TAB]||[];
c.forEach(k=>{if(k==='jumlah'){h+=`<div class="mb-2"><label class="text-xs font-bold" style="text-transform:capitalize">Jumlah (Rp)</label><input type="text" name="jumlah" data-money data-dec="0" value="${d.jumlah??0}" class="w-full border rounded p-2 mt-1" placeholder="0"></div>`;}else{h+=fld(k,d[k],lb2(k),k==='tahun'?'number':'text');}});
if(TAB==='kegiatan'){h+=selFld('bidang_id',d.bidang_id,'Bidang',`<option value="">- Pilih Bidang -</option>${BID.map(b=>`<option value="${b.id}" ${d.bidang_id==b.id?'selected':''}>${b.nama_bidang}</option>`).join('')}`)+fld('volume',Math.round(d.volume??1),'Volume','number','min="0" step="1" oninput="this.value=Math.max(0,Math.round(this.value||0))"')+selFld('satuan_id',d.satuan_id||'','Satuan',`<option value="">- Pilih Satuan -</option>${SATL.map(s=>`<option value="${s.id}" ${d.satuan_id==s.id?'selected':''}>${s.nama_satuan}</option>`).join('')}`)+fld('waktu_pelaksanaan',d.waktu_pelaksanaan,'Waktu Pelaksanaan','date')+selFld('guru_id',d.guru_id||'','Penanggung Jawab (Guru)',`<option value="">- Pilih Guru -</option>${GRU.map(g=>`<option value="${g.id}" ${(d.guru_id==g.id)?'selected':''}>${g.nama}${g.jabatan?' ('+g.jabatan+')':''}</option>`).join('')}`)+fld('sasaran',d.sasaran,'Sasaran');}
if(TAB==='rekening'){h+=selFld('jenis_belanja_id',d.jenis_belanja_id,'Jenis Belanja',`<option value="">-</option>${JB.map(b=>`<option value="${b.id}" ${d.jenis_belanja_id==b.id?'selected':''}>${b.nama}</option>`).join('')}`);}
if(['bidang','sumber_dana','jenis_belanja','satuan','rekening','kegiatan','guru'].includes(TAB)){h+=fld('keterangan',d.keterangan,'Keterangan');}
if(TAB==='tahun_anggaran'){h+=fld('tanggal_mulai',d.tanggal_mulai,'Tanggal Mulai','date')+fld('tanggal_selesai',d.tanggal_selesai,'Tanggal Selesai','date')+fld('keterangan',d.keterangan,'Keterangan');}
if(['bidang','sumber_dana','jenis_belanja','satuan','rekening','kegiatan','guru','tahun_anggaran'].includes(TAB)){const st=(d.status||'aktif').toLowerCase();const tc=s=>s.charAt(0).toUpperCase()+s.slice(1);const opt=v=>`<option value="${v}" ${st===v?'selected':''}>${tc(v)}</option>`;let so=opt('aktif')+opt('nonaktif');if(TAB==='tahun_anggaran')so+=opt('draft')+opt('selesai')+opt('dikunci');h+=selFld('status',st,'Status',so);}
if(TAB==='kegiatan'){h+=selFld('prioritas',d.prioritas||'sedang','Prioritas',['rendah','sedang','tinggi','mendesak'].map(p=>`<option value="${p}" ${d.prioritas===p?'selected':''}>${p.charAt(0).toUpperCase()+p.slice(1)}</option>`).join(''));}
h+=`<button class="w-full bg-emerald-700 text-white rounded p-2 font-bold">Simpan</button></form>`;openModal(h,'sm');}
async function masterSave(e,id){e.preventDefault();const f=new FormData(e.target);const d={act:'master_save',table:TAB,id};f.forEach((v,k)=>d[k]=v);const j=await api('x',d);if(j.ok){ok('Tersimpan');setTimeout(()=>location.reload(),800);}else err(j.msg||'Gagal');}
async function masterDel(id){if(!await ask('Hapus data ini?','Batal bila dipakai relasi lain.','Ya, Hapus'))return;const j=await api('x',{act:'master_delete',table:TAB,id});if(j.ok){ok('Dihapus');setTimeout(()=>location.reload(),800);}else err(j.msg||'Gagal');}
</script>
