<?php
$tab=$_GET['tab']??'bidang';
$tabs=['bidang'=>'Bidang','sumber_dana'=>'Sumber Dana','jenis_belanja'=>'Jenis Belanja','satuan'=>'Satuan','rekening'=>'Rekening','kegiatan'=>'Kegiatan','guru'=>'Guru','jabatan'=>'Jabatan','tahun_anggaran'=>'Tahun Anggaran'];
if(!isset($tabs[$tab]))$tab='bidang';
$cols=['bidang'=>['kode'=>'Kode','nama_bidang'=>'Nama Bidang','keterangan'=>'Keterangan','status'=>'Status'],'sumber_dana'=>['kode'=>'Kode','nama_sumber_dana'=>'Nama Sumber Dana','jumlah'=>'Pagu (Rp)','jml_anggaran'=>'Terpakai RKAM','jml_kegiatan'=>'Jml Kegiatan','keterangan'=>'Keterangan','status'=>'Status'],'jenis_belanja'=>['kode'=>'Kode','nama'=>'Nama','keterangan'=>'Keterangan','status'=>'Status'],'satuan'=>['kode'=>'Kode','nama_satuan'=>'Nama Satuan','keterangan'=>'Keterangan','status'=>'Status'],'rekening'=>['kode'=>'Kode','nama_rekening'=>'Nama Rekening','kelompok'=>'Kelompok','jenis_belanja_id'=>'Jenis Belanja','keterangan'=>'Keterangan','status'=>'Status'],'kegiatan'=>['kode'=>'Kode','nama_kegiatan'=>'Nama Kegiatan','bidang_id'=>'Bidang','volume'=>'Volume','guru_id'=>'Penanggung Jawab','waktu_pelaksanaan'=>'Waktu Pelaksanaan','prioritas'=>'Prioritas','status'=>'Status'],'guru'=>['kode'=>'Kode','nama'=>'Nama Guru','nuptk'=>'NUPTK','jabatan_id'=>'Jabatan','status'=>'Status'],'jabatan'=>['kode'=>'Kode','nama'=>'Nama Jabatan','status'=>'Status'],'tahun_anggaran'=>['tahun'=>'Tahun','tanggal_mulai'=>'Tanggal Mulai','tanggal_selesai'=>'Tanggal Selesai','status'=>'Status','keterangan'=>'Keterangan']];
if($tab==='sumber_dana'){$rows=$pdo->query("SELECT s.*,(SELECT COALESCE(SUM(rs.jumlah),0) FROM rkam_sumber_dana rs JOIN rkam k ON k.id=rs.rkam_id WHERE rs.sumber_dana_id=s.id) AS jml_anggaran,(SELECT COUNT(*) FROM rkam_sumber_dana rs JOIN rkam k ON k.id=rs.rkam_id WHERE rs.sumber_dana_id=s.id) AS jml_kegiatan FROM sumber_dana s ORDER BY s.id DESC LIMIT 200")->fetchAll();}elseif($tab==='guru'){$rows=$pdo->query("SELECT g.*,j.nama AS jabatan_nama FROM guru g LEFT JOIN jabatan j ON j.id=g.jabatan_id ORDER BY g.id DESC LIMIT 200")->fetchAll();}else{$rows=$pdo->query("SELECT * FROM `$tab` ORDER BY id DESC LIMIT 200")->fetchAll();}
$bid=$pdo->query("SELECT * FROM bidang WHERE status='aktif'")->fetchAll();
$jb=$pdo->query("SELECT * FROM jenis_belanja")->fetchAll();
$bidMap=[];foreach($bid as $b)$bidMap[$b['id']]=$b['nama_bidang'];
$jbMap=[];foreach($jb as $j)$jbMap[$j['id']]=$j['nama'];
$GRU=$pdo->query("SELECT g.*,j.nama AS jabatan_nama FROM guru g LEFT JOIN jabatan j ON j.id=g.jabatan_id ORDER BY g.nama")->fetchAll();
$gruMap=[];foreach($GRU as $g)$gruMap[$g['id']]=$g['nama'];
$JAB=$pdo->query("SELECT * FROM jabatan WHERE status='aktif' ORDER BY nama")->fetchAll();
$jabMap=[];foreach($JAB as $j)$jabMap[$j['id']]=$j['nama'];
function cellVal($tab,$c,$r,$bidMap,$jbMap,$gruMap=[],$jabMap=[]){$v=$r[$c]??'';if($c==='bidang_id')return $bidMap[$v]??'-';if($c==='jenis_belanja_id')return $jbMap[$v]??'-';if($c==='jabatan_id')return ($jabMap[$v]??$r['jabatan_nama']??$r['jabatan']??'')?:'-';if($c==='guru_id')return $gruMap[$v]??($r['penanggung_jawab']??'-');if($c==='status'||$c==='prioritas')return Helper::titleCase($v);if($c==='jml_anggaran'||$c==='jumlah')return Security::rupiah($v);if($c==='volume'&&$v!=='')return number_format((float)$v,0,',','.');if(in_array($c,['tanggal_mulai','tanggal_selesai','waktu_pelaksanaan'])&&$v)return Helper::tglIndo($v);return $v;}
?>
<div class="flex flex-wrap items-center gap-2 mb-4 no-print">
<div class="font-extrabold text-emerald-900">Master <?=$tabs[$tab]?></div>
<?php if($tab==='guru'):?>
<button onclick="guruImportModal()" title="Impor Excel Guru" class="bg-blue-600 hover:bg-blue-700 text-white h-10 px-3 rounded-2xl text-sm shadow no-print flex items-center gap-1"><i class="fa-solid fa-file-import"></i> Impor</button>
<button onclick="syncGuruSimad()" title="Sinkronkan Data Guru dari SIMAD" class="bg-indigo-600 hover:bg-indigo-700 text-white h-10 px-3 rounded-2xl text-sm shadow no-print flex items-center gap-1"><i class="fa-solid fa-rotate text-xs"></i> Sinkron SIMAD</button>
<?php endif;?>
<button onclick="masterForm(0)" title="Tambah <?=$tabs[$tab]?>" class="ml-auto bg-emerald-700 hover:bg-emerald-800 text-white w-10 h-10 rounded-2xl text-sm shadow"><i class="fa-solid fa-plus"></i></button></div>
<div class="bg-white rounded shadow overflow-auto">
<?php if(!$rows):?><div class="p-10 text-center text-gray-500">Belum ada data.<br><button onclick="masterForm(0)" title="Tambah <?=$tabs[$tab]?>" class="mt-2 bg-emerald-700 hover:bg-emerald-800 text-white w-11 h-11 rounded-2xl shadow"><i class="fa-solid fa-plus"></i></button></div>
<?php else:?><table class="w-full text-sm"><thead><tr class="bg-gray-50 border-b"><th class="p-2 w-10 text-left">No</th><?php foreach($cols[$tab] as $c=>$lbl):?><th class="p-2 text-left"><?=Security::e($lbl)?></th><?php endforeach;?><th class="p-2 no-print">Aksi</th></tr></thead>
<tbody><?php $no=1;foreach($rows as $r):?><tr class="border-b hover:bg-gray-50">
<td class="p-2"><?=$no++?></td>
<?php foreach($cols[$tab] as $c=>$lbl):?><td class="p-2"><?=Security::e(cellVal($tab,$c,$r,$bidMap,$jbMap,$gruMap,$jabMap??[]))?></td><?php endforeach;?>
<td class="p-2 whitespace-nowrap no-print"><button onclick='masterForm(<?=$r['id']?>,<?=json_encode($r,JSON_HEX_APOS|JSON_HEX_QUOT)?>)' title="Edit" class="btn-ic btn-edit"><i class="fa-solid fa-pen-to-square"></i></button> <button onclick="masterDel(<?=$r['id']?>)" title="Hapus" class="btn-ic btn-del"><i class="fa-solid fa-trash-can"></i></button></td></tr><?php endforeach;?></tbody></table><?php endif;?></div>
<script>
const TAB='<?=$tab?>',BID=<?=json_encode($bid)?>,JB=<?=json_encode($jb)?>,SATL=<?=json_encode($pdo->query("SELECT * FROM satuan WHERE status='aktif' ORDER BY nama_satuan")->fetchAll())?>,GRU=<?=json_encode($GRU)?>,JAB=<?=json_encode($JAB)?>;
function fld(n,v,l,type,extra){return `<div class="mb-2"><label class="text-xs font-bold" style="text-transform:capitalize">${l}</label><input type="${type||'text'}" name="${n}" value="${(v??'').toString().replaceAll('"','')}" class="w-full border rounded p-2 mt-1" ${extra||''}></div>`;}
function selFld(n,v,l,opts){return `<div class="mb-2"><label class="text-xs font-bold" style="text-transform:capitalize">${l}</label><select name="${n}" class="w-full border rounded p-2 mt-1">${opts}</select></div>`;}
function masterForm(id,d){d=d||{};let h=`<div class="flex justify-between items-center mb-3"><b>${id?'Edit':'Tambah'} <?=$tabs[$tab]?></b><button type="button" onclick="closeModal()" title="Tutup" class="w-8 h-8 rounded-full bg-red-50 border border-red-200 text-red-600 hover:bg-red-100 flex items-center justify-center"><i class="fa-solid fa-xmark"></i></button></div><form onsubmit="masterSave(event,${id})">`;
const LBL={kode:'Kode',nama_bidang:'Nama Bidang',nama_sumber_dana:'Nama Sumber Dana',nama:'Nama',nama_satuan:'Nama Satuan',nama_rekening:'Nama Rekening',nama_kegiatan:'Nama Kegiatan',tahun:'Tahun',kelompok:'Kelompok',keterangan:'Keterangan',bidang_id:'Bidang',jenis_belanja_id:'Jenis Belanja',status:'Status',tanggal_mulai:'Tanggal Mulai',tanggal_selesai:'Tanggal Selesai',prioritas:'Prioritas',guru_id:'Penanggung Jawab (Guru)',nama_guru:'Nama Guru',nuptk:'NUPTK',jabatan_id:'Jabatan'};
const lb=k=>LBL[k]||k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const LBL2=Object.assign({},LBL,{jumlah:'Jumlah (Rp)'});
const lb2=k=>LBL2[k]||k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const c={bidang:['nama_bidang'],sumber_dana:['nama_sumber_dana','jumlah'],jenis_belanja:['nama'],satuan:['nama_satuan'],rekening:['nama_rekening','kelompok'],kegiatan:['nama_kegiatan'],guru:['nama','nuptk'],jabatan:['nama'],tahun_anggaran:['tahun']}[TAB]||[];
c.forEach(k=>{if(k==='jumlah'){h+=`<div class="mb-2"><label class="text-xs font-bold" style="text-transform:capitalize">Jumlah (Rp)</label><input type="text" name="jumlah" data-money data-dec="0" value="${d.jumlah??0}" class="w-full border rounded p-2 mt-1" placeholder="0"></div>`;}else{h+=fld(k,d[k],lb2(k),k==='tahun'?'number':'text');}});
if(TAB==='guru'){h+=selFld('jabatan_id',d.jabatan_id||'','Jabatan',`<option value="">- Pilih Jabatan -</option>${JAB.map(j=>`<option value="${j.id}" ${String(d.jabatan_id||'')===String(j.id)?'selected':''}>${j.nama}</option>`).join('')}`);}
if(TAB==='kegiatan'){h+=selFld('bidang_id',d.bidang_id,'Bidang',`<option value="">- Pilih Bidang -</option>${BID.map(b=>`<option value="${b.id}" ${d.bidang_id==b.id?'selected':''}>${b.nama_bidang}</option>`).join('')}`)+fld('volume',Math.round(d.volume??1),'Volume','number','min="0" step="1" oninput="this.value=Math.max(0,Math.round(this.value||0))"')+selFld('satuan_id',d.satuan_id||'','Satuan',`<option value="">- Pilih Satuan -</option>${SATL.map(s=>`<option value="${s.id}" ${d.satuan_id==s.id?'selected':''}>${s.nama_satuan}</option>`).join('')}`)+fld('waktu_pelaksanaan',d.waktu_pelaksanaan,'Waktu Pelaksanaan','date')+selFld('guru_id',d.guru_id||'','Penanggung Jawab (Guru)',`<option value="">- Pilih Guru -</option>${GRU.map(g=>`<option value="${g.id}" ${(d.guru_id==g.id)?'selected':''}>${g.nama}${(g.jabatan_nama||g.jabatan)?' ('+(g.jabatan_nama||g.jabatan)+')':''}</option>`).join('')}`)+fld('sasaran',d.sasaran,'Sasaran');}
if(TAB==='rekening'){h+=selFld('jenis_belanja_id',d.jenis_belanja_id,'Jenis Belanja',`<option value="">-</option>${JB.map(b=>`<option value="${b.id}" ${d.jenis_belanja_id==b.id?'selected':''}>${b.nama}</option>`).join('')}`);}
if(['bidang','sumber_dana','jenis_belanja','satuan','rekening','kegiatan'].includes(TAB)){h+=fld('keterangan',d.keterangan,'Keterangan');}
if(TAB==='tahun_anggaran'){h+=fld('tanggal_mulai',d.tanggal_mulai,'Tanggal Mulai','date')+fld('tanggal_selesai',d.tanggal_selesai,'Tanggal Selesai','date')+fld('keterangan',d.keterangan,'Keterangan');}
if(['bidang','sumber_dana','jenis_belanja','satuan','rekening','kegiatan','guru','jabatan','tahun_anggaran'].includes(TAB)){const st=(d.status||'aktif').toLowerCase();const tc=s=>s.charAt(0).toUpperCase()+s.slice(1);const opt=v=>`<option value="${v}" ${st===v?'selected':''}>${tc(v)}</option>`;let so=opt('aktif')+opt('nonaktif');if(TAB==='tahun_anggaran')so+=opt('draft')+opt('selesai')+opt('dikunci');h+=selFld('status',st,'Status',so);}
if(TAB==='kegiatan'){h+=selFld('prioritas',d.prioritas||'sedang','Prioritas',['rendah','sedang','tinggi','mendesak'].map(p=>`<option value="${p}" ${d.prioritas===p?'selected':''}>${p.charAt(0).toUpperCase()+p.slice(1)}</option>`).join(''));}
h+=`<button class="w-full bg-emerald-700 text-white rounded p-2 font-bold">Simpan</button></form>`;openModal(h,'sm');}
async function masterSave(e,id){e.preventDefault();const f=new FormData(e.target);const d={act:'master_save',table:TAB,id};f.forEach((v,k)=>d[k]=v);const j=await api('x',d);if(j.ok){ok('Tersimpan');setTimeout(()=>location.reload(),800);}else err(j.msg||'Gagal');}
async function masterDel(id){if(!await ask('Hapus data ini?','Batal bila dipakai relasi lain.','Ya, Hapus'))return;const j=await api('x',{act:'master_delete',table:TAB,id});if(j.ok){ok('Dihapus');setTimeout(()=>location.reload(),800);}else err(j.msg||'Gagal');}
function guruTemplateXlsx(){if(typeof XLSX==='undefined'){err('Library Excel belum termuat. Cek koneksi internet.');return;}const rows=[['Kode','Nama*','NUPTK','Jabatan','Status'],['','BUDI ASHARI','1234567890123456','Guru Kelas','aktif'],['','SITI AMINAH','','Guru Mapel','aktif']];const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:12},{wch:26},{wch:20},{wch:18},{wch:10}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Guru');XLSX.writeFile(wb,'template_guru.xlsx');}
function guruImportModal(){let h=`<div class="flex justify-between items-center mb-3"><b>Impor Guru dari Excel</b><button type="button" onclick="closeModal()" title="Tutup" class="w-8 h-8 rounded-full bg-red-50 border border-red-200 text-red-600 hover:bg-red-100 flex items-center justify-center"><i class="fa-solid fa-xmark"></i></button></div>
<div class="text-sm space-y-3">
<div class="rounded-xl border border-emerald-100 bg-emerald-50/60 p-3 text-[13px]"><b>Langkah:</b> 1 Unduh template → 2 Isi Nama (wajib), NUPTK, Jabatan, Status → 3 Upload file .xlsx → 4 Impor. Baris tanpa Nama dilewati. Jabatan tak dikenal dibuat otomatis.</div>
<div class="flex flex-wrap gap-2"><button type="button" onclick="guruTemplateXlsx()" class="bg-emerald-700 hover:bg-emerald-800 text-white rounded-xl px-4 py-2 text-sm font-bold"><i class="fa-solid fa-download mr-1"></i> Unduh Template .xlsx</button></div>
<div><label class="text-xs font-bold">File Excel (.xlsx, max 5 MB)</label><input id="guruFile" type="file" accept=".xlsx" class="w-full border rounded-xl p-2 mt-1"></div>
<div id="guruPrev" class="hidden text-[13px]"></div>
<div id="guruProg" class="hidden"><div class="h-2.5 bg-emerald-100 rounded-full overflow-hidden"><div id="guruBar" class="h-2.5 rounded-full bg-emerald-600 transition-all" style="width:0%"></div></div><div id="guruTxt" class="mt-1 text-xs text-emerald-800 font-bold">0%</div></div>
<div class="flex gap-2"><button type="button" onclick="guruDoImport()" class="flex-1 bg-blue-600 hover:bg-blue-700 text-white rounded-xl p-2.5 font-bold"><i class="fa-solid fa-upload mr-1"></i> Impor Sekarang</button></div>
</div>`;openModal(h,'md');if(typeof XLSX==='undefined'){const s=document.createElement('script');s.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';document.head.appendChild(s);}document.getElementById('guruFile').addEventListener('change',guruPreview);}
async function guruPreview(ev){const f=ev.target.files[0];const box=document.getElementById('guruPrev');if(!f||!box)return;if(!/\.xlsx$/i.test(f.name)){box.classList.remove('hidden');box.innerHTML='<div class="text-red-600 font-bold">File harus .xlsx sesuai template.</div>';return;}if(typeof XLSX==='undefined'){box.classList.remove('hidden');box.innerHTML='<div class="text-amber-700">Library Excel masih dimuat, coba lagi sebentar...</div>';return;}try{const buf=await f.arrayBuffer();const wb=XLSX.read(buf,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});const n=Math.max(0,rows.length-1);box.classList.remove('hidden');box.innerHTML='<div class="rounded-xl border border-blue-100 bg-blue-50/60 p-2.5">File: <b>'+f.name+'</b> • '+(f.size/1024).toFixed(1)+' KB • <b>'+n+'</b> baris data. Header: '+(rows[0]||[]).join(' | ')+'</div>';}catch(e){box.classList.remove('hidden');box.innerHTML='<div class="text-red-600">Gagal baca file: '+e.message+'</div>';}}
async function guruDoImport(){const inp=document.getElementById('guruFile');if(!inp||!inp.files.length){err('Pilih file .xlsx dulu');return;}const f=inp.files[0];if(!/\.xlsx$/i.test(f.name)){err('File harus .xlsx sesuai template');return;}if(f.size>5*1024*1024){err('File > 5 MB');return;}if(typeof XLSX==='undefined'){err('Library Excel belum termuat. Tunggu sebentar lalu coba lagi.');return;}
const prog=document.getElementById('guruProg'),bar=document.getElementById('guruBar'),txt=document.getElementById('guruTxt');prog.classList.remove('hidden');const paint=p=>{bar.style.width=p+'%';txt.innerText=p+'%';};paint(10);
let rows;try{const buf=await f.arrayBuffer();paint(35);const wb=XLSX.read(buf,{type:'array'});paint(55);const ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});}catch(e){paint(0);prog.classList.add('hidden');err('Gagal baca Excel: '+e.message);return;}
paint(70);
const fd=new FormData();fd.append('csrf_token',window.__CSRF||CSRF);fd.append('act','guru_import');fd.append('rows',JSON.stringify(rows));
try{const r=await fetch((window.__BASE||BASE)+'api/x',{method:'POST',body:fd});paint(90);const j=await r.json();paint(100);
if(j.ok){Swal.fire({icon:'success',title:'Impor Selesai',html:'Berhasil: <b>'+j.inserted+'</b> • Dilewati: <b>'+j.skipped+'</b>'+(j.errors&&j.errors.length?'<div class="mt-2 text-left text-xs max-h-40 overflow-y-auto">'+j.errors.map(e=>'• '+e).join('<br>')+'</div>':''),confirmButtonText:'OK',confirmButtonColor:'#059669'}).then(()=>location.reload());}
else{Swal.fire({icon:'error',title:'Impor Gagal',html:(j.msg||'Gagal')+(j.errors&&j.errors.length?'<div class="mt-2 text-left text-xs max-h-40 overflow-y-auto">'+j.errors.map(e=>'• '+e).join('<br>')+'</div>':''),confirmButtonColor:'#dc2626'});}}catch(e){paint(0);err('Gagal: '+e.message);}}
async function syncGuruSimad(){
Swal.fire({title:'Menghubungi SIMAD...',text:'Mengambil data guru dari Endpoint SIMAD.',didOpen:()=>Swal.showLoading(),allowOutsideClick:false});
try{
const j=await api('x',{act:'sync_simad_guru'});
Swal.close();
if(j.ok){
Swal.fire({icon:'success',title:'Sinkronisasi Berhasil',html:`<b>${j.msg}</b><br><span class="text-xs text-gray-500">Waktu sinkron: ${j.sync_at}</span>`,confirmButtonColor:'#059669'}).then(()=>location.reload());
}else{
Swal.fire({icon:'error',title:'Sinkronisasi Gagal',text:j.msg||'Gagal sinkronisasi data dari SIMAD.',footer:'<a href="'+(window.__BASE||BASE)+'pengaturan?tab=endpoint" class="text-blue-600 underline text-xs font-bold">Atur URL Endpoint SIMAD di Pengaturan</a>'});
}
}catch(ex){Swal.close();err('Kesalahan koneksi sinkronisasi: '+ex.message);}
}
</script>
