<?php
$th=Helper::tahunAktif($pdo);
$f_tahun=(int)($_GET['tahun']??($th['id']??0));
$f_bidang=$_GET['bidang']??'';$f_sumber=$_GET['sumber']??'';$f_status=$_GET['status']??'';$q=trim($_GET['q']??'');
$w=['1=1'];$p=[];
if($f_tahun){$w[]='k.tahun_id=?';$p[]=$f_tahun;}
if($f_bidang!==''){$w[]='(k.bidang_id=? OR g.bidang_id=?)';$p[]=$f_bidang;$p[]=$f_bidang;}
if($f_status!==''){$w[]='k.status=?';$p[]=$f_status;}
if($q!==''){$w[]='(k.nama_kegiatan LIKE ? OR k.kode_kegiatan LIKE ? OR k.nomor_dokumen LIKE ?)';$p[]="%$q%";$p[]="%$q%";$p[]="%$q%";}
if($f_sumber!==''){$w[]='EXISTS(SELECT 1 FROM rkam_sumber_dana rs WHERE rs.rkam_id=k.id AND rs.sumber_dana_id=?)';$p[]=$f_sumber;}
$s=$pdo->prepare("SELECT k.*,b.nama_bidang,g.kode AS g_kode,g.nama_kegiatan AS g_nama,g.bidang_id AS g_bidang,gb.nama_bidang AS g_bidang_nama,(SELECT COALESCE(SUM(jumlah),0) FROM realisasi WHERE rkam_id=k.id) AS jml_real FROM rkam k LEFT JOIN bidang b ON b.id=k.bidang_id LEFT JOIN kegiatan g ON g.id=k.kegiatan_id LEFT JOIN bidang gb ON gb.id=g.bidang_id WHERE ".implode(' AND ',$w)." ORDER BY k.id DESC LIMIT 200");
$s->execute($p);$rows=$s->fetchAll();
$tahun=$pdo->query("SELECT * FROM tahun_anggaran ORDER BY tahun DESC")->fetchAll();
$bid=$pdo->query("SELECT * FROM bidang WHERE status='aktif'")->fetchAll();
$sum=$pdo->query("SELECT * FROM sumber_dana WHERE status='aktif'")->fetchAll();
$sat=$pdo->query("SELECT * FROM satuan WHERE status='aktif' ORDER BY nama_satuan")->fetchAll();
$keg=$pdo->query("SELECT k.*,b.nama_bidang,s.nama_satuan AS satuan_nama,g.nama AS guru_nama FROM kegiatan k LEFT JOIN bidang b ON b.id=k.bidang_id LEFT JOIN satuan s ON s.id=k.satuan_id LEFT JOIN guru g ON g.id=k.guru_id WHERE k.status='aktif' ORDER BY k.nama_kegiatan")->fetchAll();
$canAdd=in_array(Auth::role(),['superadmin','bendahara','operator']);
?>
<div class="bg-white p-3 rounded shadow mb-3 no-print">
<form class="flex flex-wrap gap-2 text-sm" method="GET" action="<?=BASE_URL?>rkam">
<input type="hidden" name="url" value="rkam">
<select name="tahun" class="border rounded p-1.5"><?php foreach($tahun as $t):?><option value="<?=$t['id']?>" <?=($f_tahun==$t['id']?'selected':'')?>><?=$t['tahun']?> (<?=$t['status']?>)</option><?php endforeach;?></select>
<select name="bidang" class="border rounded p-1.5"><option value="">Semua bidang</option><?php foreach($bid as $b):?><option value="<?=$b['id']?>" <?=($f_bidang==$b['id']?'selected':'')?>><?=Security::e($b['nama_bidang'])?></option><?php endforeach;?></select>
<select name="sumber" class="border rounded p-1.5"><option value="">Semua sumber</option><?php foreach($sum as $x):?><option value="<?=$x['id']?>" <?=($f_sumber==$x['id']?'selected':'')?>><?=Security::e($x['nama_sumber_dana'])?></option><?php endforeach;?></select>
<select name="status" class="border rounded p-1.5"><option value="">Semua status</option><?php foreach(['draft','diajukan','diverifikasi','disetujui','ditolak','direvisi','dikunci'] as $st):?><option <?=($f_status===$st?'selected':'')?>><?=$st?></option><?php endforeach;?></select>
<input name="q" value="<?=Security::e($q)?>" placeholder="Cari..." class="border rounded p-1.5">
<button class="bg-slate-700 text-white px-3 rounded">Filter</button>
<?php if($canAdd):?><button type="button" id="btnAddRkam" onclick="window.rkamForm(0)" title="Tambah RKAM" class="bg-emerald-700 hover:bg-emerald-800 text-white w-10 h-10 rounded-2xl ml-auto shadow no-print"><i class="fa-solid fa-plus"></i></button><?php endif;?>
</form></div>
<div class="bg-white rounded shadow overflow-auto">
<?php if(!$rows):?><div class="p-10 text-center text-gray-500">Belum ada data RKAM.<br><?php if($canAdd):?><button type="button" id="btnAddRkam2" onclick="window.rkamForm(0)" title="Tambah RKAM" class="mt-2 bg-emerald-700 hover:bg-emerald-800 text-white w-11 h-11 rounded-2xl shadow"><i class="fa-solid fa-plus"></i></button><?php endif;?></div>
<?php else:?><table class="w-full text-sm min-w-[900px]"><thead><tr class="bg-gray-50 border-b text-left"><th class="p-2">Nomor / Kegiatan</th><th class="p-2">Bidang</th><th class="p-2 text-right">Anggaran</th><th class="p-2 text-right">Realisasi</th><th class="p-2 text-right">Sisa</th><th class="p-2">%</th><th class="p-2">Status</th><th class="p-2 no-print">Aksi</th></tr></thead><tbody>
<?php foreach($rows as $r):$sisa=(float)$r['total_anggaran']-(float)$r['jml_real'];$pers=Helper::persen($r['jml_real'],$r['total_anggaran']);$bd=$r['g_bidang_nama']??$r['nama_bidang']??'-';?>
<tr class="border-b hover:bg-gray-50"><td class="p-2"><div class="text-xs text-gray-500"><?=Security::e($r['nomor_dokumen']??'')?> • <?=Security::e($r['kode_kegiatan']??'')?></div><a href="<?=BASE_URL?>rkam/detail/<?=$r['id']?>" class="font-semibold text-emerald-800"><?=Security::e($r['nama_kegiatan'])?></a></td>
<td class="p-2"><?=Security::e($bd)?></td><td class="p-2 text-right"><?=Security::rupiah($r['total_anggaran'])?></td><td class="p-2 text-right"><?=Security::rupiah($r['jml_real'])?></td><td class="p-2 text-right"><?=Security::rupiah($sisa)?></td><td class="p-2"><?=$pers?>%</td><td class="p-2"><?=Helper::badgeStatus($r['status'])?></td>
<td class="p-2 whitespace-nowrap no-print"><a href="<?=BASE_URL?>rkam/detail/<?=$r['id']?>" title="Detail" class="btn-ic btn-view"><i class="fa-solid fa-eye"></i></a><?php if($canAdd):?> <button onclick="rkamForm(<?=$r['id']?>)" title="Edit" class="btn-ic btn-edit"><i class="fa-solid fa-pen-to-square"></i></button> <button onclick="rkamDel(<?=$r['id']?>)" title="Hapus" class="btn-ic btn-del"><i class="fa-solid fa-trash-can"></i></button><?php endif;?></td></tr>
<?php endforeach;?></tbody></table><?php endif;?></div>
<script>
let REK=<?=json_encode($pdo->query("SELECT * FROM rekening WHERE status='aktif' ORDER BY kode")->fetchAll())?>,SAT=<?=json_encode($sat)?>,SUM=<?=json_encode($sum)?>,KEG=<?=json_encode($keg)?>;
fetch(BASE+'api/master_opt',{method:'POST',body:new URLSearchParams({csrf_token:CSRF,act:'master_opt'})}).then(r=>r.json()).then(j=>{if(j.ok){if(j.data.rekening&&j.data.rekening.length)REK=j.data.rekening;if(j.data.sumber&&j.data.sumber.length)SUM=j.data.sumber;if(j.data.satuan&&j.data.satuan.length)SAT=j.data.satuan;if(j.data.kegiatan&&j.data.kegiatan.length)KEG=j.data.kegiatan;}});
async function rkamForm(id){
let d={tahun_id:'<?=$f_tahun?>',nama_kegiatan:'',items:[{uraian:'',volume:1,satuan:'',harga_satuan:0}],sumber:[]};
if(id){const r=await fetch(BASE+'api/rkam_get',{method:'POST',body:new URLSearchParams({csrf_token:CSRF,act:'rkam_get',id})}).then(r=>r.json());if(!r.ok){err(r.msg);return;}d=r.data;}
const bid=<?=json_encode($bid)?>,tah=<?=json_encode($tahun)?>;
let h=`<div class="flex justify-between items-center mb-2"><b>${id?'Edit':'Tambah'} RKAM</b><button type="button" onclick="closeModal()" title="Tutup" class="w-8 h-8 rounded-full bg-red-50 border border-red-200 text-red-600 hover:bg-red-100 flex items-center justify-center"><i class="fa-solid fa-xmark"></i></button></div>
<div class="mb-3 rounded-xl border border-blue-100 bg-blue-50/70 p-2.5 text-[11px] text-slate-600">Alur: <b>1 Tahun</b> → <b>2 Kegiatan Master</b> → <b>3 Item</b> → <b>4 Sumber (balance)</b> → Simpan. Data pokok tidak diketik ulang — ikut Master.</div>
<form onsubmit="rkamSave(event,${id})" class="text-sm space-y-3">
<div class="grid md:grid-cols-2 gap-2">
<div><label class="text-xs font-bold">1. Tahun *</label><select name="tahun_id" class="w-full border rounded p-2">${tah.map(t=>`<option value="${t.id}" ${d.tahun_id==t.id?'selected':''}>${t.tahun}</option>`).join('')}</select></div>
<div><label class="text-xs font-bold">2. Kegiatan (Master) *</label><select id="rkKeg" name="kegiatan_id" onchange="pickKeg(this.value)" class="w-full border rounded p-2"><option value="">- Pilih Kegiatan -</option></select></div></div>
<div id="kegInfo" class="rounded-xl border border-emerald-100 bg-emerald-50/60 p-3 text-xs space-y-1"></div>
<div class="grid md:grid-cols-2 gap-2">
<div><label class="text-xs font-bold">Prioritas (Ikut Kegiatan)</label><input type="hidden" name="prioritas" id="rkPrior" value="${d.prioritas||''}"><div id="priorInfo" class="w-full border rounded p-2 bg-gray-50 text-slate-700">-</div></div>
<div><label class="text-xs font-bold">Keterangan</label><input name="keterangan" placeholder="Keterangan" value="${(d.keterangan||'').replaceAll('"','')}" class="w-full border rounded p-2"></div></div>
<div class="font-bold">3. Item Anggaran <button type="button" onclick="addItem()" title="Tambah Item" class="ml-2 bg-blue-600 hover:bg-blue-700 text-white w-7 h-7 rounded-xl text-xs shadow"><i class="fa-solid fa-plus"></i></button></div>
<div id="items" class="space-y-2"></div>
<div class="text-right font-bold">Total: <span id="grand">Rp 0</span></div>
<div class="font-bold">4. Sumber Dana (Wajib Balance) <button type="button" onclick="addSumber()" title="Tambah Sumber" class="ml-2 bg-blue-600 hover:bg-blue-700 text-white w-7 h-7 rounded-xl text-xs shadow"><i class="fa-solid fa-plus"></i></button></div>
<div id="sums" class="space-y-2"></div>
<div class="text-right text-xs">Total sumber: <span id="gsum">Rp 0</span> • <span id="bdiff"></span></div>
<button id="btnSave" type="submit" class="w-full bg-emerald-700 text-white rounded p-2 font-bold disabled:opacity-50">Simpan RKAM</button></form>`;
openModal(h,'lg');renderItems(d.items&&d.items.length?d.items:[{uraian:'',volume:1,satuan:'',harga_satuan:0}]);renderSums(d.sumber&&d.sumber.length?d.sumber:[]);fillKeg(d.kegiatan_id||'');}
function fillKeg(cur){const s=document.getElementById('rkKeg');if(!s)return;const w=s.closest('.dd');if(w){w.parentNode.insertBefore(s,w);w.remove();delete s.dataset.dd;}s.innerHTML='<option value="">- Pilih Kegiatan -</option>'+KEG.map(k=>`<option value="${k.id}" ${String(k.id)===String(cur||'')?'selected':''}>${k.kode} — ${k.nama_kegiatan} (${k.nama_bidang||'-'})</option>`).join('');renderKegInfo(cur);syncPrior(cur);if(typeof ddify==='function')ddify(document.getElementById('modalBox'));}
function cv(v){return (v===null||v===undefined||v==='')?'-':v;}
function renderKegInfo(id){const box=document.getElementById('kegInfo');if(!box)return;const k=KEG.find(x=>String(x.id)===String(id||''));if(!k){box.innerHTML='<span class="text-gray-500">Langkah 1: pilih Tahun, Langkah 2: pilih Kegiatan Master. Semua data pokok otomatis ikut master (tidak ketik ulang).</span>';return;}const pr=String(k.prioritas||'-');const pj=k.guru_nama||k.penanggung_jawab||'';box.innerHTML=`<div class="grid md:grid-cols-2 gap-x-4 gap-y-1"><div><b>Kode:</b> ${cv(k.kode)}</div><div><b>Bidang:</b> ${cv(k.nama_bidang)}</div><div class="md:col-span-2"><b>Kegiatan:</b> ${cv(k.nama_kegiatan)}</div><div class="md:col-span-2"><b>Sasaran:</b> ${cv(k.sasaran)}</div><div><b>Volume Master:</b> ${cv(k.volume)} ${cv(k.satuan_nama||'')}</div><div><b>Waktu:</b> ${cv(k.waktu_pelaksanaan)}</div><div><b>Penanggung Jawab:</b> ${pj?cv(pj):'<b class="text-red-600">Belum Diisi — Pilih Guru di Master</b>'}</div><div><b>Prioritas Master:</b> ${pr.charAt(0).toUpperCase()+pr.slice(1)}</div><div class="md:col-span-2"><b>Keterangan Master:</b> ${cv(k.keterangan)}</div></div><div class="mt-1 text-[11px] text-emerald-700">Sinkron penuh: semua field di atas ikut Master. RKAM hanya tambah Prioritas RKAM, Keterangan RKAM, Item & Sumber.</div>`;}
function pickKeg(id){renderKegInfo(id);syncPrior(id);const k=KEG.find(x=>String(x.id)===String(id||''));if(!k)return;const ket=document.querySelector('#modalBox input[name=keterangan]');if(ket&&!ket.value.trim()&&k.keterangan)ket.value=k.keterangan;syncFirstItem(k);}
function syncPrior(id){const k=KEG.find(x=>String(x.id)===String(id||''));const h=document.getElementById('rkPrior'),box=document.getElementById('priorInfo');if(!h||!box)return;const p=(k&&k.prioritas)?k.prioritas:'';h.value=p;box.textContent=p?p.charAt(0).toUpperCase()+p.slice(1):'-';}
function syncFirstItem(k){const rows=document.querySelectorAll('#modalBox .irow');if(!rows.length||!k)return;rows.forEach((r,i)=>{if(rows.length>1&&i>0)return;const u=r.querySelector('.iu');if(u)u.value=k.nama_kegiatan||u.value;const v=r.querySelector('.iv');if(v)v.value=Math.max(0,Math.round(parseFloat(k.volume??v.value??1)||0));const s=r.querySelector('select.is');if(s&&k.satuan_nama){const w=s.closest('.dd');if(w){w.parentNode.insertBefore(s,w);w.remove();delete s.dataset.dd;}let has=[...s.options].some(o=>o.value===k.satuan_nama);if(!has){const o=document.createElement('option');o.value=k.satuan_nama;o.textContent=k.satuan_nama;s.appendChild(o);}s.value=k.satuan_nama;}});calc();if(typeof ddify==='function')setTimeout(()=>ddify(document.getElementById('modalBox')),0);if(typeof bindMoney==='function')setTimeout(()=>bindMoney(document.getElementById('modalBox')),0);}
function satOpts(cur){const v=(cur||'').toString().toLowerCase();return SAT.map(s=>`<option value="${s.nama_satuan}" ${v===s.nama_satuan.toLowerCase()?'selected':''}>${s.nama_satuan}</option>`).join('');}
function rekOpts(cur){return REK.map(r=>`<option value="${r.kode}" ${String(cur||'')===String(r.kode)?'selected':''}>${r.kode} — ${r.nama_rekening}</option>`).join('');}
function itemRow(it){it=it||{readonly:false};const cur=it.satuan||it.satuan_text||'';const inList=SAT.some(s=>s.nama_satuan.toLowerCase()===(cur||'').toString().toLowerCase());const ro=it.readonly?'readonly style="background:#f1f5f9"':'';const roS=it.readonly?'disabled style="background:#f1f5f9"':'';const rk=it.kode_rekening||it.rekening_id||'';return `<div class="grid grid-cols-12 gap-2 irow bg-gray-50 p-2 rounded-xl border border-emerald-100">
<div class="col-span-3"><label class="text-[11px] font-bold">Kode Rekening</label><select class="w-full border rounded-xl p-1.5 ir bg-white">${rekOpts(rk)}${rk&&!REK.some(r=>String(r.kode)===String(rk))?`<option value="${String(rk).replaceAll('"','')}" selected>${String(rk).replace(/</g,'&lt;')}</option>`:''}</select></div>
<div class="col-span-3"><label class="text-[11px] font-bold">Uraian * (Ikut Kegiatan)</label><input ${ro} class="w-full border rounded-xl p-1.5 iu" placeholder="Otomatis dari kegiatan" value="${(it.uraian||'').replaceAll('"','')}"></div>
<div class="col-span-2"><label class="text-[11px] font-bold">Volume (Ikut)</label><input ${ro} type="number" min="0" step="1" class="w-full border rounded-xl p-1.5 iv" value="${Math.round(it.volume??1)}" oninput="calc()"></div>
<div class="col-span-2"><label class="text-[11px] font-bold">Satuan (Ikut)</label><select ${roS} class="w-full border rounded-xl p-1.5 is bg-white">${satOpts(inList?cur:'')}${(!inList&&cur)?`<option value="${cur.replaceAll('"','')}" selected>${cur.replaceAll('<','&lt;')}</option>`:''}</select></div>
<div class="col-span-2"><label class="text-[11px] font-bold">Harga Satuan (Rp)</label><input type="text" inputmode="numeric" data-money data-dec="0" class="w-full border rounded-xl p-1.5 ih" value="${Math.round(it.harga_satuan??0)}" oninput="calc()"></div>
<div class="col-span-1 flex items-end"><button type="button" onclick="this.closest('.irow').remove();calc()" title="Hapus Item" class="text-red-600 w-full">x</button></div>
<div class="col-span-12 text-right text-xs">Jumlah: <b class="ij">${rp((it.volume||0)*(it.harga_satuan||0))}</b></div></div>`;}
function renderItems(a){const k=KEG.find(x=>String(x.id)===String((document.getElementById('rkKeg')||{}).value||''));document.getElementById('items').innerHTML=(a||[]).map(it=>itemRow(syncItem(it,k))).join('');calc();if(typeof ddify==='function')setTimeout(()=>ddify(document.getElementById('modalBox')),0);if(typeof bindMoney==='function')setTimeout(()=>bindMoney(document.getElementById('modalBox')),0);}
function syncItem(it,k){if(!k)return it;return Object.assign({},it,{uraian:k.nama_kegiatan||it.uraian,volume:(k.volume??it.volume),satuan:k.satuan_nama||it.satuan||it.satuan_text,readonly:true});}
function addItem(){const k=KEG.find(x=>String(x.id)===String((document.getElementById('rkKeg')||{}).value||''));document.getElementById('items').insertAdjacentHTML('beforeend',itemRow(syncItem({},k)));calc();if(typeof ddify==='function')setTimeout(()=>ddify(document.getElementById('modalBox')),0);if(typeof bindMoney==='function')setTimeout(()=>bindMoney(document.getElementById('modalBox')),0);}
function paguOf(id){const s=SUM.find(x=>String(x.id)===String(id||''));return s?parseFloat(s.jumlah||0):0;}
function sumHint(id){const p=paguOf(id);return p>0?`<div class="text-[10px] text-gray-500 mt-0.5">Pagu: ${rp(p)}</div>`:`<div class="text-[10px] text-gray-400 mt-0.5">Pagu: -</div>`;}
function renderSums(a){const opts=SUM.map(s=>({id:s.id,nama:s.nama_sumber_dana,jumlah:s.jumlah}));document.getElementById('sums').innerHTML=(a||[]).map(s=>{const cur=s.sumber_dana_id||s.id||'';return `<div class="grid grid-cols-2 gap-2 srow items-start bg-gray-50 p-2 rounded-xl border border-emerald-100"><div class="min-w-0"><label class="text-[11px] font-bold">Sumber Dana</label><select class="sid w-full border rounded-xl p-1.5 bg-white" onchange="chgSumSrc(this)">${opts.map(o=>`<option value="${o.id}" ${String(cur)===String(o.id)?'selected':''}>${o.nama}</option>`).join('')}</select><div class="sumPagu mt-0.5 leading-tight">${sumHint(cur)}</div></div><div class="min-w-0"><label class="text-[11px] font-bold">Jumlah (Rp)</label><div class="flex gap-1 items-center"><input type="text" inputmode="numeric" data-money data-dec="0" class="w-full border rounded-xl p-1.5 sj" value="${s.jumlah||0}" oninput="calcSum()"><button type="button" onclick="this.closest('.srow').remove();calcSum()" title="Hapus Sumber" class="text-red-600 px-1 shrink-0">x</button></div><div class="mt-0.5 leading-tight text-[10px] text-transparent">.</div></div></div>`;}).join('');if(!a||!a.length)addSumberRow();calcSum();if(typeof ddify==='function')setTimeout(()=>ddify(document.getElementById('modalBox')),0);if(typeof bindMoney==='function')setTimeout(()=>bindMoney(document.getElementById('modalBox')),0);}
function addSumberRow(){const opts=SUM.map(s=>`<option value="${s.id}">${s.nama_sumber_dana}</option>`).join('');document.getElementById('sums').insertAdjacentHTML('beforeend',`<div class="grid grid-cols-2 gap-2 srow items-start bg-gray-50 p-2 rounded-xl border border-emerald-100"><div class="min-w-0"><label class="text-[11px] font-bold">Sumber Dana</label><select class="sid w-full border rounded-xl p-1.5 bg-white" onchange="chgSumSrc(this)">${opts}</select><div class="sumPagu mt-0.5 leading-tight">${sumHint(SUM[0]?SUM[0].id:'')}</div></div><div class="min-w-0"><label class="text-[11px] font-bold">Jumlah (Rp)</label><div class="flex gap-1 items-center"><input type="text" inputmode="numeric" data-money data-dec="0" class="w-full border rounded-xl p-1.5 sj" value="0" oninput="calcSum()"><button type="button" onclick="this.closest('.srow').remove();calcSum()" title="Hapus Sumber" class="text-red-600 px-1 shrink-0">x</button></div><div class="mt-0.5 leading-tight text-[10px] text-transparent">.</div></div></div>`);calcSum();if(typeof ddify==='function')setTimeout(()=>ddify(document.getElementById('modalBox')),0);if(typeof bindMoney==='function')setTimeout(()=>bindMoney(document.getElementById('modalBox')),0);}
function chgSumSrc(sel){const row=sel.closest('.srow');if(!row)return;const box=row.querySelector('.sumPagu');if(box)box.innerHTML=sumHint(sel.value);calcSum();}
function addSumber(){addSumberRow();}
function getItems(){return [...document.querySelectorAll('.irow')].map(r=>{const s=r.querySelector('select.is');const h=r.querySelector('.ih');const hv=h?(h.dataset.dec!==undefined?parseID(h.value):parseFloat(h.value)):0;const rk=r.querySelector('select.ir');return {rekening_id:'',kode_rekening:rk?rk.value:'',uraian:r.querySelector('.iu').value,volume:Math.max(0,Math.round(parseFloat(r.querySelector('.iv').value)||0)),satuan:s?s.value:'',harga_satuan:hv||0};});}
function getSums(){return [...document.querySelectorAll('.srow')].map(r=>{const s=r.querySelector('select.sid');const j=r.querySelector('.sj');return {id:s?s.value:'',jumlah:j?parseID(j.value):0};});}
function calc(){let t=0;document.querySelectorAll('.irow').forEach(r=>{const v=parseFloat(r.querySelector('.iv').value)||0;const hi=r.querySelector('.ih');const h=hi?parseID(hi.value):0;r.querySelector('.ij').innerText=rp(v*h);t+=v*h;});const g=document.getElementById('grand');if(g)g.innerText=rp(t);updateDiff();}
function calcSum(){let t=0;document.querySelectorAll('.sj').forEach(i=>t+=parseID(i.value));const g=document.getElementById('gsum');if(g)g.innerText=rp(t);updateDiff();}
document.addEventListener('money',e=>{if(e.target&&e.target.closest&&(e.target.closest('.irow')||e.target.closest('#modalBox')))calc();if(e.target&&e.target.closest&&(e.target.closest('.srow')||e.target.closest('#fReal')))calcSum();if(typeof rcalc==='function'&&e.target&&e.target.id==='rh')rcalc();});
function sumItems(){let t=0;document.querySelectorAll('.irow').forEach(r=>{const hi=r.querySelector('.ih');t+=(parseFloat(r.querySelector('.iv').value)||0)*(hi?parseID(hi.value):0);});return Math.round(t*100)/100;}
function sumSumber(){let t=0;document.querySelectorAll('.sj').forEach(i=>t+=parseID(i.value));return Math.round(t*100)/100;}
function updateDiff(){const el=document.getElementById('bdiff');if(!el)return;const t=sumItems(),s=sumSumber(),d=Math.round((s-t)*100)/100;if(Math.abs(d)<0.01){el.innerHTML='<b class="text-emerald-600">Balance</b>';}else{el.innerHTML='Selisih: <b class="text-red-600">'+rp(Math.abs(d))+'</b>'+(s>t?' (sumber lebih besar)':' (sumber kurang)');}}
function autoBalance(){const t=sumItems();const rows=[...document.querySelectorAll('.srow')];if(!rows.length){err('Belum ada baris sumber dana');return;}const vals=rows.map(r=>parseFloat(r.querySelector('.sj').value)||0);let idx=vals.findIndex(v=>v>0);if(vals.filter(v=>v>0).length!==1){idx=0;rows.forEach((r,i)=>{if(i>0)r.querySelector('.sj').value=0;});}rows[idx].querySelector('.sj').value=t;calcSum();}
async function rkamSave(e,id){e.preventDefault();const btn=document.getElementById('btnSave');if(btn){btn.disabled=true;btn.innerText='Menyimpan...';}try{const ks=document.getElementById('rkKeg');const kegId=ks?ks.value:'';if(!kegId){err('Langkah 2 belum: pilih Kegiatan Master dulu');return;}const sums=getSums();if(!sums.length){err('Langkah 4 belum: minimal 1 sumber dana');return;}const ids=sums.map(s=>String(s.id));if(ids.some(v=>!v||v==='0')){err('Pilih sumber dana dulu');return;}if(new Set(ids).size!==ids.length){err('Sumber dana ganda. Gabung jadi 1 baris.');return;}const items=getItems();if(!items.length||!items.some(it=>it.uraian.trim()!=='')){err('Langkah 3 belum: minimal 1 item anggaran dengan uraian');return;}const t=sumItems(),s=sumSumber();if(t<=0){err('Total anggaran harus > 0');return;}if(Math.abs(s-t)>0.01){err('Langkah 4 belum balance: sumber ('+s.toLocaleString('id-ID')+') != anggaran ('+t.toLocaleString('id-ID')+'). Sesuaikan jumlah tiap sumber.');return;}const f=new FormData(e.target);const d={act:'rkam_save',id,tahun_id:f.get('tahun_id'),kegiatan_id:kegId,prioritas:f.get('prioritas'),keterangan:f.get('keterangan'),items:JSON.stringify(items),sumber:JSON.stringify(sums)};const j=await api('x',d);if(j.ok){ok('Tersimpan');setTimeout(()=>location.reload(),800);}else err(j.msg||'Gagal');}finally{if(btn){btn.disabled=false;btn.innerText='Simpan RKAM';}}}
async function rkamDel(id){if(!await ask('Hapus RKAM ini?','Item + sumber ikut terhapus.','Ya, Hapus'))return;const j=await api('x',{act:'rkam_delete',id});if(j.ok){ok('Dihapus');setTimeout(()=>location.reload(),800);}else err(j.msg);}
window.rkamForm=rkamForm;window.rkamSave=rkamSave;window.rkamDel=rkamDel;window.addItem=addItem;window.addSumber=addSumber;window.getItems=getItems;window.getSums=getSums;window.calc=calc;window.calcSum=calcSum;window.sumItems=sumItems;window.sumSumber=sumSumber;window.updateDiff=updateDiff;window.fillKeg=fillKeg;window.pickKeg=pickKeg;window.syncFirstItem=syncFirstItem;window.syncItem=syncItem;window.syncPrior=syncPrior;window.chgSumSrc=chgSumSrc;window.rekOpts=rekOpts;
['btnAddRkam','btnAddRkam2'].forEach(b=>{const el=document.getElementById(b);if(el)el.addEventListener('click',ev=>{ev.preventDefault();window.rkamForm(0);});});
</script>
